stages:
  - test
  - build
  - release

execute_tests:
  stage: test
  script:
    - php /usr/local/bin/composer install
    - php vendor/bin/phpunit --coverage-text
    - php vendor/bin/phpcs --standard=PSR2 src/Makaira/
    - php vendor/bin/phpmd src/Makaira/ text codesize,design

execute_build:
  stage: build
  only:
    - tags
  script:
    - echo "checking Versions-Tag '${CI_COMMIT_REF_NAME}'"
    - VERSIONSTEST=`cat metadata.php | grep "${CI_COMMIT_REF_NAME}"`

release:
  tags:
    - marmalade-docker
  stage: release
  image: node:14
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - /usr/local/share/.cache/yarn/v6
  script:
    - yarn
    - yarn release
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
