types:
  - test
  - build

execute_tests:
  type: test
  script:
    - composer install
    - php vendor/bin/phpunit --coverage-text
    - php vendor/bin/phpcs --standard=PSR2 src/Makaira/
    - php vendor/bin/phpmd src/Makaira/ text codesize,design

execute_build:
  type: build
  only:
    - tags
  script:
    - VERSIONSTEST=`cat metadata.php | grep "${CI_BUILD_REF_NAME}"`
    - echo "${VERSIONSTEST}"
    - echo "${VERSIONSTEST}"
    - if [ "$VERSIONSTEST" = "0" ]; then exit 42; fi
