types:
  - test
  - build

execute_tests:
  type: test
  script:
    - php5.6 /usr/local/bin/composer install
    - php5.6 vendor/bin/phpunit --coverage-text
    - php5.6 vendor/bin/phpcs --standard=PSR2 src/Makaira/
    - php5.6 vendor/bin/phpmd src/Makaira/ text codesize,design

execute_build:
  type: build
  only:
    - tags
  script:
    - echo "checking Versions-Tag '${CI_COMMIT_REF_NAME}'"
    - VERSIONSTEST=`cat metadata.php | grep "${CI_COMMIT_REF_NAME}"`
