types:
  - test

execute_tests:
  type: test
  script:
    - composer install
    - php vendor/bin/phpunit --coverage-text
    - php vendor/bin/phpcs --standard=PSR2 src/Makaira/
    - php vendor/bin/phpmd src/Makaira/ text cleancode,codesize,design
