
services:
  _defaults:
    autowire: true
    public: false
    bind:
      $oxLang: '@makaira.connect.oxid.language'

  # oxid.database
  Makaira\Connect\Database\DoctrineDatabase:
    class: Makaira\Connect\Database\DoctrineDatabase
    public: true

  # oxid.table_translator
  Makaira\Connect\Utils\TableTranslator:
    class: Makaira\Connect\Utils\TableTranslator
    public: true
    arguments:
      - ['oxarticles', 'oxartextends', 'oxattribute', 'oxcategories', 'oxmanufacturers', 'oxobject2attribute']

  # content_parsers.oxid.smarty
  # makaira.content_parser
  Makaira\Connect\Utils\OxidSmartyParser:
    class: Makaira\Connect\Utils\OxidSmartyParser
    arguments:
      $oxUtilsView: '@makaira.connect.oxid.utils_view'

  # oxid.language
  makaira.connect.oxid.language:
    class: OxidEsales\Eshop\Core\Language
    factory: ['OxidEsales\Eshop\Core\Registry', 'getLang']
    public: true

  # oxid.language
  makaira.connect.oxid.utils_server:
    class: OxidEsales\Eshop\Core\UtilsServer
    factory: ['OxidEsales\Eshop\Core\Registry', 'getUtilsServer']

  makaira.connect.oxid.article:
    class: OxidEsales\Eshop\Application\Model\Article
    factory: ['OxidEsales\Eshop\Core\Registry', 'get']
    arguments: ['OxidEsales\Eshop\Application\Model\Article']

  makaira.connect.oxid.seo_encoder_category:
    class: OxidEsales\Eshop\Application\Model\SeoEncoderCategory
    factory: ['OxidEsales\Eshop\Core\Registry', 'get']
    arguments: ['OxidEsales\Eshop\Application\Model\SeoEncoderCategory']

  makaira.connect.oxid.seo_encoder_manufacturer:
    class: OxidEsales\Eshop\Application\Model\SeoEncoderManufacturer
    factory: ['OxidEsales\Eshop\Core\Registry', 'get']
    arguments: ['OxidEsales\Eshop\Application\Model\SeoEncoderManufacturer']

  makaira.connect.oxid.seo_encoder_article:
    class: OxidEsales\Eshop\Application\Model\SeoEncoderArticle
    factory: ['OxidEsales\Eshop\Core\Registry', 'get']
    arguments: ['OxidEsales\Eshop\Application\Model\SeoEncoderArticle']

  makaira.connect.oxid.utils_view:
    class: OxidEsales\Eshop\Core\UtilsView
    factory: ['OxidEsales\Eshop\Core\Registry', 'getUtilsView']

  makaira.connect.oxid.config:
    class: OxidEsales\Eshop\Core\Config
    factory: ['OxidEsales\Eshop\Core\Registry', 'getConfig']
    # public: true

  # makaira.connect.http_client
  Makaira\HttpClient\Signing:
    class: Makaira\HttpClient\Signing
    arguments:
      $aggregate: '@Makaira\HttpClient\Curl'
      $sharedSecret: "@=service('makaira.connect.oxid.config').getShopConfVar('makaira_connect_secret', null, 'module:makaira/connect')"

  Makaira\HttpClient\Curl:
    class: Makaira\HttpClient\Curl
    arguments:
      $timeout: "@=service('makaira.connect.oxid.config').getConfigParam('makairaConnectTimeout', 2)"

  # makaira.connect.utils.boostfields
  Makaira\Connect\Utils\BoostFields:
    class: Makaira\Connect\Utils\BoostFields
    public: true

  # makaira.connect.category_inheritance
  Makaira\Connect\Utils\CategoryInheritance:
    class: Makaira\Connect\Utils\CategoryInheritance
    public: true
    arguments:
      $useCategoryInheritance: "@=service('makaira.connect.oxid.config').getShopConfVar('makaira_connect_category_inheritance', null, 'module:makaira/connect')"
      $categoryAggregationId: "@=service('makaira.connect.oxid.config').getShopConfVar('makaira_connect_categorytree_id', null, 'module:makaira/connect')"

  # makaira.connect.suggester
  Makaira\Connect\Core\Autosuggester:
    class: Makaira\Connect\Core\Autosuggester
    public: true

  # makaira.connect.searchhandler
  Makaira\Connect\SearchHandler:
    class: Makaira\Connect\SearchHandler
    public: true
    arguments:
      $httpClient: '@Makaira\HttpClient\Signing'
      $url: "@=service('makaira.connect.oxid.config').getShopConfVar('makaira_application_url', null, 'module:makaira/connect')"
      $instance: "@=service('makaira.connect.oxid.config').getShopConfVar('makaira_instance', null, 'module:makaira/connect')"

  # makaira.connect.utils.tokengenerator
  Makaira\Connect\Utils\TokenGenerator:
    class: Makaira\Connect\Utils\TokenGenerator
    public: true

  # makaira.connect.recommendationhandler
  Makaira\Connect\RecommendationHandler:
    class: Makaira\Connect\RecommendationHandler
    public: true
    arguments:
      $httpClient: '@Makaira\HttpClient\Signing'
      $url: "@=service('makaira.connect.oxid.config').getShopConfVar('makaira_application_url', null, 'module:makaira/connect')"
      $instance: "@=service('makaira.connect.oxid.config').getShopConfVar('makaira_instance', null, 'module:makaira/connect')"

  # makaira.connect.operational_intelligence
  Makaira\Connect\Utils\OperationalIntelligence:
    class: Makaira\Connect\Utils\OperationalIntelligence
    public: true
    arguments:
      $utilsServer: '@makaira.connect.oxid.utils_server'

  Makaira\Connect\Command\TouchAllCommand:
    class: Makaira\Connect\Command\TouchAllCommand
    public: true
    tags:
    - { name: 'console.command' }

  Makaira\Connect\Command\CleanupCommand:
    class: Makaira\Connect\Command\CleanupCommand
    public: true
    tags:
    - { name: 'console.command' }

  # makaira.connect.repository
  Makaira\Connect\Repository:
    class: Makaira\Connect\Repository
    public: true

  # makaira.connect.repository.user
  Makaira\Connect\Repository\UserRepository:
    class: Makaira\Connect\Repository\UserRepository
    public: true

  makaira.connect.modifiers.common.product2shop:
    class: Makaira\Connect\Modifier\Common\ShopModifier
    arguments:
      $isMultiShop: "@=service('makaira.connect.oxid.config').isMall()"
      $mappingTable: 'oxarticles2shop'
    tags:
      - { name: 'kernel.event_listener', event: 'makaira.importer.modifier.product', priority: 1000, method: addModifier }
      - { name: 'kernel.event_listener', event: 'makaira.importer.modifier.variant', priority: 1000, method: addModifier }

  makaira.connect.modifiers.product.boost_field:
    class: Makaira\Connect\Modifier\Product\BoostFieldModifier
    tags:
      - { name: 'kernel.event_listener', event: 'makaira.importer.modifier.product', priority: 1000, method: addModifier }

  makaira.connect.modifiers.common.category2shop:
    class: Makaira\Connect\Modifier\Common\ShopModifier
    arguments:
      $isMultiShop: "@=service('makaira.connect.oxid.config').isMall()"
      $mappingTable: 'oxcategories2shop'
    tags:
      - { name: 'kernel.event_listener', event: 'makaira.importer.modifier.category', priority: 1000, method: addModifier }

  makaira.connect.modifiers.common.manufacturer2shop:
    class: Makaira\Connect\Modifier\Common\ShopModifier
    arguments:
      $isMultiShop: "@=service('makaira.connect.oxid.config').isMall()"
      $mappingTable: 'oxmanufacturers2shop'
    tags:
      - { name: 'kernel.event_listener', event: 'makaira.importer.modifier.manufacturer', priority: 1000, method: addModifier }

  makaira.connect.modifiers.common.attribute:
    class: Makaira\Connect\Modifier\Common\AttributeModifier
    arguments:
      $activeSnippet: "@=service('makaira.connect.oxid.article').getSqlActiveSnippet(true)"
      $attributeInt: "@=service('makaira.connect.oxid.config').getShopConfVar('makaira_attribute_as_int', null, 'module:makaira/connect')"
      $attributeFloat: "@=service('makaira.connect.oxid.config').getShopConfVar('makaira_attribute_as_float', null, 'module:makaira/connect')"
    tags:
      - { name: 'kernel.event_listener', event: 'makaira.importer.modifier.product', priority: 1000, method: addModifier }
      - { name: 'kernel.event_listener', event: 'makaira.importer.modifier.variant', priority: 1000, method: addModifier }

  makaira.connect.modifiers.product.variant.attributes:
    class: Makaira\Connect\Modifier\Product\VariantAttributesModifier
    arguments:
      $activeSnippet: "@=service('makaira.connect.oxid.article').getSqlActiveSnippet(true)"
      $attributeInt: "@=service('makaira.connect.oxid.config').getShopConfVar('makaira_attribute_as_int', null, 'module:makaira/connect')"
      $attributeFloat: "@=service('makaira.connect.oxid.config').getShopConfVar('makaira_attribute_as_float', null, 'module:makaira/connect')"
    tags:
      - { name: 'kernel.event_listener', event: 'makaira.importer.modifier.product', priority: 1000, method: addModifier }

  makaira.connect.modifiers.common.vat:
    class: Makaira\Connect\Modifier\Common\PriceModifier
    arguments:
      $isNetto: "@=service('makaira.connect.oxid.config').getConfigParam('blEnterNetPrice')"
      $showNetto: "@=service('makaira.connect.oxid.config').getConfigParam('blShowNetPrice')"
      $defaultVAT: "@=service('makaira.connect.oxid.config').getConfigParam('dDefaultVAT')"
    tags:
      - { name: 'kernel.event_listener', event: 'makaira.importer.modifier.product', priority: 1000, method: addModifier }
      - { name: 'kernel.event_listener', event: 'makaira.importer.modifier.variant', priority: 1000, method: addModifier }

  makaira.connect.modifiers.common.active:
    class: Makaira\Connect\Modifier\Common\ActiveModifier
    tags:
      - { name: 'kernel.event_listener', event: 'makaira.importer.modifier.product', priority: 1000, method: addModifier }
      - { name: 'kernel.event_listener', event: 'makaira.importer.modifier.variant', priority: 1000, method: addModifier }
      - { name: 'kernel.event_listener', event: 'makaira.importer.modifier.category', priority: 1000, method: addModifier }
      - { name: 'kernel.event_listener', event: 'makaira.importer.modifier.manufacturer', priority: 1000, method: addModifier }

  makaira.connect.modifiers.common.stock:
    class: Makaira\Connect\Modifier\Common\StockModifier
    tags:
      - { name: 'kernel.event_listener', event: 'makaira.importer.modifier.product', priority: 1000, method: addModifier }
      - { name: 'kernel.event_listener', event: 'makaira.importer.modifier.variant', priority: 1000, method: addModifier }

  makaira.connect.modifiers.common.longdescription:
    class: Makaira\Connect\Modifier\Common\LongDescriptionModifier
    arguments:
      $contentParser: '@Makaira\Connect\Utils\OxidSmartyParser'
      $parseThroughSmarty: "@=service('makaira.connect.oxid.config').getShopConfVar('bl_perfParseLongDescinSmarty', null, 'module:makaira/connect')"
    tags:
      - { name: 'kernel.event_listener', event: 'makaira.importer.modifier.product', priority: 1000, method: addModifier }
      - { name: 'kernel.event_listener', event: 'makaira.importer.modifier.variant', priority: 1000, method: addModifier }

  makaira.connect.modifiers.common.zerodatetime:
    class: Makaira\Connect\Modifier\Common\ZeroDateTimeModifier
    tags:
      - { name: 'kernel.event_listener', event: 'makaira.importer.modifier.product', priority: 1000, method: addModifier }
      - { name: 'kernel.event_listener', event: 'makaira.importer.modifier.variant', priority: 1000, method: addModifier }
      - { name: 'kernel.event_listener', event: 'makaira.importer.modifier.category', priority: 1000, method: addModifier }

  makaira.connect.modifiers.category.url:
    class: Makaira\Connect\Modifier\Common\UrlModifier
    arguments:
      $objectClass: OxidEsales\Eshop\Application\Model\Category
      $encoder: '@makaira.connect.oxid.seo_encoder_category'
    tags:
      - { name: 'kernel.event_listener', event: 'makaira.importer.modifier.category', priority: 1000, method: addModifier }

  makaira.connect.modifiers.manufacturer.url:
    class: Makaira\Connect\Modifier\Common\UrlModifier
    arguments:
      $objectClass: OxidEsales\Eshop\Application\Model\Manufacturer
      $encoder: '@makaira.connect.oxid.seo_encoder_manufacturer'
    tags:
      - { name: 'kernel.event_listener', event: 'makaira.importer.modifier.manufacturer', priority: 1000, method: addModifier }

  makaira.connect.modifiers.product.url:
    class: Makaira\Connect\Modifier\Common\UrlModifier
    arguments:
      $objectClass: OxidEsales\Eshop\Application\Model\Article
      $encoder: '@makaira.connect.oxid.seo_encoder_article'
    tags:
      - { name: 'kernel.event_listener', event: 'makaira.importer.modifier.product', priority: 1000, method: addModifier }

  makaira.connect.modifiers.common.blacklist.product:
    class: Makaira\Connect\Modifier\Common\BlacklistModifier
    arguments:
      $blacklistedFields: "@=service('makaira.connect.oxid.config').getShopConfVar('makaira_field_blacklist_product', null, 'module:makaira/connect')"
    tags:
      - { name: 'kernel.event_listener', event: 'makaira.importer.modifier.product', priority: -1, method: addModifier }
      - { name: 'kernel.event_listener', event: 'makaira.importer.modifier.variant', priority: -1, method: addModifier }

  makaira.connect.modifiers.common.blacklist.category:
    class: Makaira\Connect\Modifier\Common\BlacklistModifier
    arguments:
      $blacklistedFields: "@=service('makaira.connect.oxid.config').getShopConfVar('makaira_field_blacklist_category', null, 'module:makaira/connect')"
    tags:
      - { name: 'kernel.event_listener', event: 'makaira.importer.modifier.category', priority: -1, method: addModifier }

  makaira.connect.modifiers.common.blacklist.manufacturer:
    class: Makaira\Connect\Modifier\Common\BlacklistModifier
    arguments:
      $blacklistedFields: "@=service('makaira.connect.oxid.config').getShopConfVar('makaira_field_blacklist_manufacturer', null, 'module:makaira/connect')"
    tags:
      - { name: 'kernel.event_listener', event: 'makaira.importer.modifier.manufacturer', priority: -1, method: addModifier }

  makaira.connect.modifiers.product.category:
    class: Makaira\Connect\Modifier\Product\CategoryModifier
    tags:
      - { name: 'kernel.event_listener', event: 'makaira.importer.modifier.product', priority: 1000, method: addModifier }

  makaira.connect.modifiers.product.mainCategory:
    class: Makaira\Connect\Modifier\Product\MainCategoryModifier
    arguments:
      $encoder: '@makaira.connect.oxid.seo_encoder_category'
    tags:
      - { name: 'kernel.event_listener', event: 'makaira.importer.modifier.product', priority: 1000, method: addModifier }

  makaira.connect.modifiers.category.hierarchy:
    class: Makaira\Connect\Modifier\Category\HierarchyModifier
    tags:
      - { name: 'kernel.event_listener', event: 'makaira.importer.modifier.category', priority: 1000, method: addModifier }

  makaira.connect.modifiers.category.subcategories:
    class: Makaira\Connect\Modifier\Category\SubcategoriesModifier
    tags:
      - { name: 'kernel.event_listener', event: 'makaira.importer.modifier.category', priority: 1000, method: addModifier }

  makaira.connect.modifiers.common.default.values:
    class: Makaira\Connect\Modifier\Common\DefaultProperties
    tags:
      - { name: 'kernel.event_listener', event: 'makaira.importer.modifier.product', priority: 9999, method: addModifier }
      - { name: 'kernel.event_listener', event: 'makaira.importer.modifier.variant', priority: 9999, method: addModifier }
      - { name: 'kernel.event_listener', event: 'makaira.importer.modifier.category', priority: 9999, method: addModifier }
      - { name: 'kernel.event_listener', event: 'makaira.importer.modifier.manufacturer', priority: 9999, method: addModifier }

  # makaira.connect.repository.product
  Makaira\Connect\Repository\ProductRepository:
    class: Makaira\Connect\Repository\ProductRepository
    public: true
    arguments:
      $modifiers: '@makaira.connect.repository.product.mofifier_list'
    tags:
    - { name: 'kernel.event_listener', event: 'makaira.connect.repository', priority: 1000, method: 'addRepository' }

  makaira.connect.repository.product.mofifier_list:
    class: Makaira\Connect\Repository\ModifierList
    arguments:
      $tag: 'makaira.importer.modifier.product'

  # makaira.connect.repository.variant
  Makaira\Connect\Repository\VariantRepository:
    class: Makaira\Connect\Repository\VariantRepository
    public: true
    arguments:
      $modifiers: '@makaira.connect.repository.variant.mofifier_list'
    tags:
    - { name: 'kernel.event_listener', event: 'makaira.connect.repository', priority: 990, method: 'addRepository' }

  makaira.connect.repository.variant.mofifier_list:
    class: Makaira\Connect\Repository\ModifierList
    arguments:
      $tag: 'makaira.importer.modifier.variant'

  # makaira.connect.repository.category
  Makaira\Connect\Repository\CategoryRepository:
    class: Makaira\Connect\Repository\CategoryRepository
    public: true
    arguments:
      $modifiers: '@makaira.connect.repository.category.mofifier_list'
    tags:
    - { name: 'kernel.event_listener', event: 'makaira.connect.repository', priority: 980, method: 'addRepository' }

  makaira.connect.repository.category.mofifier_list:
    class: Makaira\Connect\Repository\ModifierList
    arguments:
      $tag: 'makaira.importer.modifier.category'

  # makaira.connect.repository.manufacturer
  Makaira\Connect\Repository\ManufacturerRepository:
    class: Makaira\Connect\Repository\ManufacturerRepository
    public: true
    arguments:
      $modifiers: '@makaira.connect.repository.manufacturer.mofifier_list'
    tags:
    - { name: 'kernel.event_listener', event: 'makaira.connect.repository', priority: 970, method: 'addRepository' }

  makaira.connect.repository.manufacturer.mofifier_list:
    class: Makaira\Connect\Repository\ModifierList
    arguments:
      $tag: 'makaira.importer.modifier.manufacturer'

  # makaira.connect.version.handler
  Makaira\Connect\VersionHandler:
    class: Makaira\Connect\VersionHandler
    public: true
